### PR TITLE
Fixed start position issue #49

### PR DESCRIPTION
**Pull request by hideaki-j**
## Summary
I fixed this problem (which @KDercksen pointed out) that my previous fix does not work for the example "Paris. Paris. Paris. Paris.".

## Note
- In this pull request, I only fix the bug in "mention_detection.py". Regarindg fixing utils.py, more discussion is needed.
- Note that the bug in "mention_detection.py" only appears when the user specifies the "span" (am I correct?).

## Test
- I checked this fix by an easy unit-level test for two examples mentioned in issue #49.
- Please note that I do not have a full-environment to do an interface test currently. After this merge is finished, I will check this fix using API. If anyone could do an interface test before merging this fix, that would be appreciated.

#### For example 1 (in issue #49)
- Checked mention "Paris" between 381 and 545 become 449 (not 128).

```
print(processed)

####### Output #########
# {'API_DOC': 
# ["Hi. I need to book a vacation to Long Beach between August 25 and September 3. Departure is from Paris\tWould you like to depart Paris on September 6th?\tPreferably by the 3rd. Is there anything available?\tSorry, looks like there is nothing available from Paris to Long Beach on September 3rd.\tI'm not quite sure I understand, is there anything available leaving Long Beach to go to Paris between August 25 and September 3rd?\tWould you like to depart Paris on September 6th?\tNo. I would like to leave Long Beach around the 25th of August to go to Paris for some reason. What is so confusing about that!?\tYou can leave Long Beach, USA and go to Paris, France on Tuesday, August 30th. Will I book this?\tFinally! No, don't book yet, I would like to know more about the hotel. Is there free breakfast?\tThere is free wifi.\tLook buddy, is there free breakfast or not? Tell me, am I gonna get eggs, toast, cereal, etc? You know? The good stuff?\tThere is free wifi at the hotel. \tWhat is the price of this toastless package?\tThis package costs 2191.55USD.\tIs this the cheapest option?\tYes, this is the cheapest option from Long Beach to Paris.\tAnd the hotel has how many stars?\tMuse Hotel has 2.0 stars.\tOk I will book this one.\tGreat. You will leave Paris on September 7", 
# [(97, 5), (128, 5), (254, 5), (381, 5), (449, 5), (545, 5), (642, 5), (1127, 5), (1241, 5)]]}

dataset, processed_sentences, splits = mention_detection.split_text(processed)
print(dataset)

####### Output ########
#{'API_DOC': {0: ['Hi.', []],
#  1: ['I need to book a vacation to Long Beach between August 25 and September 3.',
#   []],
#  2: ['Departure is from Paris\tWould you like to depart Paris on September 6th?',
#   [['Paris', 97, 102], ['Paris', 128, 133]]],
#  3: ['Preferably by the 3rd.', []],
#  4: ['Is there anything available?', []],
#  5: ['Sorry, looks like there is nothing available from Paris to Long Beach on September 3rd.',
#   [['Paris', 254, 259]]],
#  6: ["I'm not quite sure I understand, is there anything available leaving Long Beach to go to Paris between August 25 and September 3rd?",
#   [['Paris', 381, 386]]],
#  7: ['Would you like to depart Paris on September 6th?',
#   ---> [['Paris', 449, 454]]],
#  8: ['No. I would like to leave Long Beach around the 25th of August to go to Paris for some reason.',
#   [['Paris', 545, 550]]],
#  9: ['What is so confusing about that!?', []],
#  10: ['You can leave Long Beach, USA and go to Paris, France on Tuesday, August 30th.',
#   [['Paris', 642, 647]]],
#  11: ['Will I book this?', []],
#  12: ['Finally!', []],
#  13: ["No, don't book yet, I would like to know more about the hotel.", []],
#  14: ['Is there free breakfast?', []],
#  15: ['There is free wifi.', []],
#  16: ['Look buddy, is there free breakfast or not?', []],
#  17: ['Tell me, am I gonna get eggs, toast, cereal, etc?', []],
#  18: ['You know?', []],
#  19: ['The good stuff?', []],
#  20: ['There is free wifi at the hotel.', []],
#  21: ['What is the price of this toastless package?', []],
#  22: ['This package costs 2191.55USD.', []],
#  23: ['Is this the cheapest option?', []],
#  24: ['Yes, this is the cheapest option from Long Beach to Paris.',
#   [['Paris', 1127, 1132]]],
#  25: ['And the hotel has how many stars?', []],
#  26: ['Muse Hotel has 2.0 stars.', []],
#  27: ['Ok I will book this one.', []],
#  28: ['Great.', []],
#  29: ['You will leave Paris on September 7', [['Paris', 1241, 1246]]]}}
```

#### For example 2
```
print(processed)

##### OUTPUT ######
# {'API_DOC': ['Paris. Paris. Paris. Paris.', [(0, 5), (7, 5), (14, 5), (21, 5)]]}

dataset, processed_sentences, splits = mention_detection.split_text(processed)
print(dataset)

##### OUTPUT ######
# {'API_DOC': {0: ['Paris.', [['Paris', 0, 5]]],
#   1: ['Paris.', [['Paris', 7, 12]]],
#   2: ['Paris.', [['Paris', 14, 19]]],
#   3: ['Paris.', [['Paris', 21, 26]]]}}


```

### CODE REVIEW

**Comment by KDercksen** [comment]
>     * Note that the bug in "mention_detection.py" only appears when the user specifies the "span" (am I correct?).
I think this is correct. That variable is also referenced [here](https://github.com/informagi/REL/blob/master/REL/mention_detection.py#L139) but not used any further, so if spans contained thererin are wrong it would not show up.

---

Regarding the problem in `utils.py`, perhaps we can link mentions to sentences by some sort of identifier that will be different even if the sentence text is the same. Maybe this info is already in the objects, I will do a bit more investigation first to figure out what the different variables consist of again (mainly `mentions_dataset` and `predictions` in `process_results` function).

Do you think we should include it in this PR @hideaki-j ? If not, we can merge this one and create a separate PR for the `utils.py` bug.

**Comment by hideaki-j** [comment]
> Regarding the problem in utils.py, perhaps we can link mentions to sentences by some sort of identifier that will be different even if the sentence text is the same. 

I agree with you. This is the best way to solve this problem.

> Do you think we should include it in this PR @hideaki-j ? If not, we can merge this one and create a separate PR for the utils.py bug.

I am happy to join this PR, but creating a separate PR for utils.py is also a good idea. It is up to you:) (Personally, I prefer the second solution since I am not a professional for GitHub and I would like to avoid any risk to affect the original PR badly). 
Please note that I do not have a full-environment to do an interface test currently. After my new PC arrives, I will create a full-environment for REL, but it will take a month.

> Maybe this info is already in the objects, I will do a bit more investigation first to figure out what the different variables consist of again (mainly mentions_dataset and predictions in process_results function).

Thanks. I will investigate too 👍

**Comment by hideaki-j** [comment]
Hi! @KDercksen 

I have fixed the problem that we have discussed. My fix is based on our discussion in #49. For more details, please see the [diff](https://github.com/informagi/REL/pull/51/commits/ae9adcc464cb407fd6deb5ca2bc91c486206c4c1).

The correction summary is:
- I used your idea proposed [here](https://github.com/informagi/REL/issues/49#issuecomment-713404387)
  - For the first code block, in which you create ```cum_offsets```, I created a new function [```create_cum_offsets```](https://github.com/informagi/REL/pull/51/commits/ae9adcc464cb407fd6deb5ca2bc91c486206c4c1#diff-8a6ab9b0b41895eb1be86a3d1f1f57a468818450ed8de4061edbd248c25fe2ecR66).
- As I mentioned in "how to fix" section in [my previous comment in issue #49](https://github.com/informagi/REL/issues/49#issuecomment-713681716), I created [```sent```](https://github.com/informagi/REL/pull/51/commits/ae9adcc464cb407fd6deb5ca2bc91c486206c4c1#diff-c81cfd328ec03cdc690f6c52b7291592aa923e594f8cc911ea1fd9bdc46abaf0R184) in ```find_mention``` function. This ```sent``` is passed to [```process_results```](https://github.com/informagi/REL/pull/51/commits/ae9adcc464cb407fd6deb5ca2bc91c486206c4c1#diff-ce85c6daaaf93a0267b415590217f30aa529725540f136d6a0c4479067f2ccd4R132) function.

I tested for all three samples (example 1, 2, and whitespace example) for ```len(spans)>0``` case and ```len(spans)==0``` case. In case I missed something, could you double-check?

**Comment by KDercksen** [comment]
So this should be closed?

**Pull request closed without merging**
